services:
  postgresql:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    ports:
      - "10503:5432"
    # networks:
      # - team
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql.conf"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgreVol:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
volumes:
  postgreVol:
    external: true