services:
  storage:
    image: storage
    container_name: storage
    ports:
      - "10502:10502"
    # networks:
      # - team
    restart: unless-stopped
    environment:
      MONGO_DB_PASSWD: ${MONGO_DB_PASSWD}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      JWT_SECRET: ${DJANGO_SECRET_KEY}
  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger
    ports:
      - "10522:8080"
    restart: unless-stopped
    volumes:
      - /home/monzo/IaC/docker/storage/swagger.json:/storage/swagger.json:ro
    environment:
      SWAGGER_JSON: /storage/swagger.json
    depends_on:
      - storage