services:
  nginx:
    image: nginx
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    # networks:
      # - team
    restart: unless-stopped
    volumes:
      - /home/monzo/Frontend/lyuk-alert/build/:/usr/share/nginx/html
      - /home/monzo/IaC/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt
      - nginxVol:/var/log/
volumes:
  nginxVol:
    external: true