services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "10501:27017"
    # networks:
      # - team
    restart: unless-stopped
    volumes:
      - mongoVol:/data/db
    command: --wiredTigerCacheSizeGB 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: OLsfTeam
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u admin -p OLsfTeam --quiet | grep 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  mongoVol:
    external: true